import type { BalanceSheetTutorialStep } from "../types/balance-sheet-tutorial";

export const JELAJAH_NERACA_TUTORIAL_STEPS: BalanceSheetTutorialStep[] = [
    {
        id: "jn-step-1",
        target: "#neraca-status-card",
        title: "1. Status Keseimbangan Neraca",
        content: "Kartu ini menampilkan status Neraca Seimbang (Balanced) serta perbandingan total Aset terhadap Liabilitas dan Ekuitas.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "jn-step-2",
        target: "#neraca-filter-date-group",
        title: "2. Cutoff Tanggal & Preset",
        content: "Tentukan tanggal penutupan pembukuan atau gunakan dropdown kalender untuk memilih preset tanggal cepat.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "jn-step-3",
        target: "#neraca-switch-dk",
        title: "3. Switch Detail D/K",
        content: "Switch ini menampilkan kolom mutasi Debit dan Kredit pada setiap pos akun dalam tabel.",
        placement: "bottom",
        skipScroll: true,
        ensureDkOn: true,
    },
    {
        id: "jn-step-4",
        target: "#neraca-section-header-assets",
        fallbackTarget: "#neraca-section-assets",
        title: "4. Struktur Seksi Aset",
        content: "Menampilkan rincian harta perusahaan (Kas, Bank, Piutang, Persediaan Barang) beserta sub-total dan persentase porsi terhadap total aset.",
        placement: "bottom",
        skipScroll: true,
        ensureDkOn: true,
    },
    {
        id: "jn-step-5",
        target: "#neraca-section-header-liabilities",
        fallbackTarget: "#neraca-section-liabilities-equity",
        title: "5. Seksi Kewajiban (Liabilitas)",
        content: "Seksi ini memuat seluruh kewajiban finansial perusahaan, baik hutang usaha jangka pendek maupun jangka panjang kepada pihak lain.",
        placement: "bottom",
        skipScroll: true,
        ensureDkOn: true,
    },
    {
        id: "jn-step-6",
        target: "#neraca-section-header-equity",
        title: "6. Seksi Ekuitas",
        content: "Seksi ini menampilkan modal pemilik, dana cadangan, serta akumulasi Sisa Hasil Usaha (SHU) tahun berjalan dan tahun lalu.",
        placement: "bottom",
        skipScroll: true,
        ensureDkOn: true,
    },
    {
        id: "jn-step-7",
        target: ".neraca-detail-btn",
        fallbackTarget: "#neraca-section-header-assets",
        title: "7. Rincian Kategori Transaksi",
        content: "Klik tombol Detail pada akun untuk melihat rincian breakdown transaksi per kategori pada akun terkait.",
        placement: "bottom",
        skipScroll: true,
        ensureDkOn: true,
        ensureDetailOpen: true,
    },
    {
        id: "jn-step-8",
        target: "#neraca-btn-print",
        title: "8. Cetak Laporan PDF",
        content: "Unduh atau cetak dokumen resmi neraca keuangan toko Anda dalam format PDF siap pakai.",
        placement: "bottom",
        skipScroll: true,
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
