import type { Asset } from "@/features/assets/types";
import type { AssetTutorialMeta } from "../types/assets-tutorial";

export const ASSET_TUTORIAL_LIST: AssetTutorialMeta[] = [
    {
        id: "catat_aset",
        title: "Pencatatan Aset Baru",
        description: "Panduan mencatat perolehan aset baru baik secara tunai, kredit, atau saldo awal.",
        category: "Manajemen Aset",
        stepCount: 7,
        badge: "Alur Utama",
        isAvailable: true,
    },
    {
        id: "edit_aset",
        title: "Edit Informasi Aset",
        description: "Perbarui nama, kode, nilai residu, dan catatan pada data aset terdaftar.",
        category: "Manajemen Aset",
        stepCount: 3,
        isAvailable: true,
    },
    {
        id: "susut_single",
        title: "Penyusutan Aset Tunggal",
        description: "Catat transaksi penyusutan berkala untuk satu item aset tertentu.",
        category: "Penyusutan",
        stepCount: 4,
        badge: "Satuan",
        isAvailable: true,
    },
    {
        id: "susut_bulk",
        title: "Penyusutan Massal (Bulk)",
        description: "Lakukan penyusutan kolektif untuk banyak aset sekaligus dengan kalkulasi otomatis.",
        category: "Penyusutan",
        stepCount: 4,
        badge: "Massal",
        isAvailable: true,
    },
    {
        id: "detail_hapus",
        title: "Detail Riwayat & Hapus Aset",
        description: "Lihat riwayat penyusutan aset dan langkah aman penghapusan data aset.",
        category: "Manajemen Aset",
        stepCount: 5,
        isAvailable: true,
    },
    {
        id: "kategori_aset",
        title: "Kelola Kategori Aset & CoA",
        description: "Buat kategori aset baru beserta pemetaan ke akun Akuntansi (CoA Asset, Akumulasi, Beban).",
        category: "Kategori Aset",
        stepCount: 5,
        badge: "Pengaturan",
        isAvailable: true,
    },
    {
        id: "jual_aset",
        title: "Penjualan & Pelepasan Aset",
        description: "Panduan lengkap pelepasan aset tetap, kalkulasi otomatis laba/rugi, pemilihan akun offset, dan simulasi jurnal GL.",
        category: "Pelepasan Aset",
        stepCount: 9,
        badge: "Fitur Baru",
        isAvailable: true,
    },
];

export const MOCK_ASSETS: Asset[] = [
    {
        uid: "tutorial-mock-asset-1",
        nomor_aset: "AST-0001",
        kode_aset: "KTR-LPT-01",
        nama: "Laptop ThinkPad T14 (Demo)",
        asset_category_uid: "tutorial-mock-cat-1",
        tanggal_perolehan: "2024-01-10",
        harga_perolehan: 18000000,
        nilai_residu: 3000000,
        akumulasi_penyusutan_awal: 0,
        total_penyusutan: 3000000,
        nilai_buku: 15000000,
        sumber_perolehan: "kas",
        status: "aktif",
        catatan: "Laptop operasional tim IT",
        can_delete: true,
        penyusutan_count: 2,
        category: {
            uid: "tutorial-mock-cat-1",
            kode: "KTR",
            nama: "Peralatan Kantor",
        },
    },
    {
        uid: "tutorial-mock-asset-2",
        nomor_aset: "AST-0002",
        kode_aset: "KTR-PRN-02",
        nama: "Printer Epson L3210 (Demo)",
        asset_category_uid: "tutorial-mock-cat-1",
        tanggal_perolehan: "2022-05-15",
        harga_perolehan: 2500000,
        nilai_residu: 500000,
        akumulasi_penyusutan_awal: 0,
        total_penyusutan: 2000000,
        nilai_buku: 500000,
        sumber_perolehan: "kas",
        status: "habis_susut",
        catatan: "Printer kasir - sudah habis nilai susut",
        can_delete: false,
        penyusutan_count: 12,
        category: {
            uid: "tutorial-mock-cat-1",
            kode: "KTR",
            nama: "Peralatan Kantor",
        },
    },
];
