import type { CatalogProduct } from "../../types";
import type { Store } from "@/features/stores/types";
import type { ProductStore } from "@/features/master/products/types";
import type { CatalogTutorialMeta } from "../types/catalog-tutorial";

export const CATALOG_TUTORIAL_LIST: CatalogTutorialMeta[] = [
    {
        id: "pembuatan_katalog",
        title: "1. Pembuatan & Pengelolaan Master Katalog Produk",
        description: "Panduan lengkap membuat produk master holding: barcode, identitas, kategori, brand, HPP beli, target margin %, harga ritel, dan skema grosir bertingkat.",
        category: "Katalog Master",
        stepCount: 10,
        badge: "Produk Master",
        isAvailable: true,
    },
    {
        id: "distribusi_toko",
        title: "2. Manajemen Pendistribusian Produk ke Toko Cabang",
        description: "Panduan mendistribusikan produk master ke cabang: ringkasan master, preset harga global, skema grosir seragam, dan kustomisasi harga khusus per cabang.",
        category: "Distribusi Cabang",
        stepCount: 12,
        badge: "Multi-Toko",
        isAvailable: true,
    },
];

export const MOCK_CATALOG_STORES: Store[] = [
    {
        uid: "store-surabaya-hq",
        nama: "Toko Pusat Surabaya",
        is_central: true,
        alamat: "Jl. Pemuda No. 45, Surabaya",
        telepon: "031-5551234",
        is_active: true,
    },
    {
        uid: "store-malang",
        nama: "Cabang Malang",
        is_central: false,
        alamat: "Jl. Ijen No. 12, Malang",
        telepon: "0341-555678",
        is_active: true,
    },
    {
        uid: "store-jakarta",
        nama: "Cabang Jakarta Barat",
        is_central: false,
        alamat: "Jl. Kebon Jeruk No. 88, Jakarta Barat",
        telepon: "021-5559876",
        is_active: true,
    },
];

export const MOCK_CATALOG_PRODUCTS: CatalogProduct[] = [
    {
        uid: "mock-catalog-prod-1",
        nama: "Kopi Arabika Premium 250g",
        merek: "Nusantara Coffee",
        barcode: "8997012345678",
        harga: 65000,
        harga_jual: 65000,
        harga_beli: 45000,
        margin: 30.77,
        stok: 120,
        satuan: "Pcs",
        unit: {
            uid: "unit-pcs",
            nama: "Pieces",
            simbol: "Pcs",
        },
        category_uid: "cat-beverage",
        category: {
            uid: "cat-beverage",
            nama: "Minuman & Kopi",
            deskripsi: null,
        },
        brand_uid: "brand-nusantara",
        brand: {
            uid: "brand-nusantara",
            nama: "Nusantara Coffee",
            deskripsi: null,
        },
        status: "active",
        is_jasa: false,
        is_raw_material: false,
        is_grosir: true,
        harga_grosir: 58000,
        min_qty_grosir: 10,
        created_by_toko: {
            uid: "store-surabaya-hq",
            nama: "Toko Pusat Surabaya",
        },
        created_by_user: {
            uid: "user-admin",
            name: "Administrator Holding",
        },
        product_stores: [
            {
                product_uid: "mock-catalog-prod-1",
                store_uid: "store-surabaya-hq",
                harga_beli: 45000,
                harga_jual: 65000,
                margin: 30.77,
                stok: 50,
                status: "active",
                is_grosir: true,
                harga_grosir: 58000,
                min_qty_grosir: 10,
            },
            {
                product_uid: "mock-catalog-prod-1",
                store_uid: "store-malang",
                harga_beli: 45000,
                harga_jual: 65000,
                margin: 30.77,
                stok: 40,
                status: "active",
                is_grosir: true,
                harga_grosir: 58000,
                min_qty_grosir: 10,
            },
            {
                product_uid: "mock-catalog-prod-1",
                store_uid: "store-jakarta",
                harga_beli: 45000,
                harga_jual: 68000,
                margin: 33.82,
                stok: 30,
                status: "active",
                is_grosir: true,
                harga_grosir: 60000,
                min_qty_grosir: 10,
            },
        ],
    },
    {
        uid: "mock-catalog-prod-2",
        nama: "Biji Kopi Mentah Green Beans",
        merek: "Java Estate",
        barcode: "8997012345685",
        harga: 110000,
        harga_jual: 110000,
        harga_beli: 80000,
        margin: 27.27,
        stok: 50,
        satuan: "Kg",
        unit: {
            uid: "unit-kg",
            nama: "Kilogram",
            simbol: "Kg",
        },
        category_uid: "cat-raw",
        category: {
            uid: "cat-raw",
            nama: "Bahan Mentah",
            deskripsi: null,
        },
        brand_uid: "brand-java",
        brand: {
            uid: "brand-java",
            nama: "Java Estate",
            deskripsi: null,
        },
        status: "active",
        is_jasa: false,
        is_raw_material: true,
        is_grosir: false,
        created_by_toko: {
            uid: "store-surabaya-hq",
            nama: "Toko Pusat Surabaya",
        },
        created_by_user: {
            uid: "user-admin",
            name: "Administrator Holding",
        },
    },
    {
        uid: "mock-catalog-prod-3",
        nama: "Jasa Servis & Kalibrasi Mesin Espresso",
        merek: "Internal Tech",
        barcode: "8997012345692",
        harga: 150000,
        harga_jual: 150000,
        harga_beli: 50000,
        margin: 66.67,
        stok: 999,
        satuan: "Sesi",
        unit: {
            uid: "unit-sesi",
            nama: "Sesi Layanan",
            simbol: "Sesi",
        },
        category_uid: "cat-service",
        category: {
            uid: "cat-service",
            nama: "Jasa & Layanan",
            deskripsi: null,
        },
        brand_uid: "brand-internal",
        brand: {
            uid: "brand-internal",
            nama: "Internal Tech",
            deskripsi: null,
        },
        status: "active",
        is_jasa: true,
        is_raw_material: false,
        is_grosir: false,
        created_by_toko: {
            uid: "store-surabaya-hq",
            nama: "Toko Pusat Surabaya",
        },
        created_by_user: {
            uid: "user-admin",
            name: "Administrator Holding",
        },
    },
    {
        uid: "mock-catalog-prod-4",
        nama: "Sirup Karamel Gourmet 750ml",
        merek: "Sweet Craft",
        barcode: "8997012345708",
        harga: 48000,
        harga_jual: 48000,
        harga_beli: 32000,
        margin: 33.33,
        stok: 85,
        satuan: "Botol",
        unit: {
            uid: "unit-btl",
            nama: "Botol",
            simbol: "Btl",
        },
        category_uid: "cat-beverage",
        category: {
            uid: "cat-beverage",
            nama: "Minuman & Kopi",
            deskripsi: null,
        },
        brand_uid: "brand-sweet",
        brand: {
            uid: "brand-sweet",
            nama: "Sweet Craft",
            deskripsi: null,
        },
        status: "active",
        is_jasa: false,
        is_raw_material: false,
        is_grosir: true,
        harga_grosir: 42000,
        min_qty_grosir: 6,
        created_by_toko: {
            uid: "store-surabaya-hq",
            nama: "Toko Pusat Surabaya",
        },
        created_by_user: {
            uid: "user-admin",
            name: "Administrator Holding",
        },
    },
];

export const MOCK_CATALOG_ASSIGNMENTS: ProductStore[] = [
    {
        product_uid: "mock-catalog-prod-1",
        store_uid: "store-surabaya-hq",
        harga_beli: 45000,
        harga_jual: 65000,
        margin: 30.77,
        stok: 50,
        status: "active",
        is_grosir: true,
        harga_grosir: 58000,
        min_qty_grosir: 10,
    },
    {
        product_uid: "mock-catalog-prod-1",
        store_uid: "store-malang",
        harga_beli: 45000,
        harga_jual: 65000,
        margin: 30.77,
        stok: 40,
        status: "active",
        is_grosir: true,
        harga_grosir: 58000,
        min_qty_grosir: 10,
    },
    {
        product_uid: "mock-catalog-prod-1",
        store_uid: "store-jakarta",
        harga_beli: 45000,
        harga_jual: 68000,
        margin: 33.82,
        stok: 30,
        status: "active",
        is_grosir: true,
        harga_grosir: 60000,
        min_qty_grosir: 10,
    },
];
