import type { Transaction } from "@/features/transactions/types";
import type { User } from "@/types/auth";

const DUMMY_CASHIER_USER: User = {
    uid: "user-dummy-01",
    name: "Siti Rahma (Kasir)",
    username: "siti_kasir",
    email: "siti@toko.local",
    store_uid: "store-01",
    status: "active",
    roles: ["kasir"],
    permissions: [],
};

const DUMMY_SUPERVISOR_USER: User = {
    uid: "user-spv-01",
    name: "Hendra Wijaya (Supervisor)",
    username: "hendra_spv",
    email: "hendra@toko.local",
    store_uid: "store-01",
    status: "active",
    roles: ["admin"],
    permissions: [],
};

export const DUMMY_TRANSACTIONS: Transaction[] = [
    {
        uid: "trx-dummy-001",
        store_uid: "store-01",
        user_uid: "user-dummy-01",
        nomor_transaksi: "TRX-20260916-001",
        nama_transaksi: "Pesanan Minuman & Pastry (Meja 04)",
        subtotal: 150000,
        diskon: 0,
        diskon_grosir: 0,
        pajak: 0,
        total: 150000,
        status: "completed",
        metode_pembayaran: "cash",
        nominal_bayar: 200000,
        kembalian: 50000,
        jenis_kartu: null,
        nomor_kartu_akhir: null,
        cash_received: 200000,
        cash_amount: 150000,
        card_amount: 0,
        debt_amount: 0,
        created_at: "2026-09-16T08:45:00.000000Z",
        updated_at: "2026-09-16T08:45:00.000000Z",
        user: DUMMY_CASHIER_USER,
        items: [
            {
                uid: "item-01",
                product_uid: "prod-01",
                nama_produk: "Kopi Arabika Specialty 250g",
                barcode: "BRC-KOP-01",
                harga_beli: 65000,
                harga_satuan: 95000,
                kuantitas: 1,
                diskon_item: 0,
                subtotal: 95000,
            },
            {
                uid: "item-02",
                product_uid: "prod-02",
                nama_produk: "Teh Melati Premium 100g",
                barcode: "BRC-TEH-02",
                harga_beli: 20000,
                harga_satuan: 35000,
                kuantitas: 1,
                diskon_item: 0,
                subtotal: 35000,
            },
            {
                uid: "item-03",
                product_uid: "prod-03",
                nama_produk: "Susu Segar Pasteurisasi 1L",
                barcode: "BRC-SSU-03",
                harga_beli: 15000,
                harga_satuan: 20000,
                kuantitas: 1,
                diskon_item: 0,
                subtotal: 20000,
            },
        ],
    },
    {
        uid: "trx-dummy-002",
        store_uid: "store-01",
        user_uid: "user-dummy-01",
        nomor_transaksi: "TRX-20260916-002",
        nama_transaksi: "Bahan Baku & Sirup Buah",
        subtotal: 350000,
        diskon: 0,
        diskon_grosir: 0,
        pajak: 0,
        total: 350000,
        status: "completed",
        metode_pembayaran: "card",
        nominal_bayar: 350000,
        kembalian: 0,
        jenis_kartu: "Debit BCA",
        nomor_kartu_akhir: "8821",
        cash_received: 0,
        cash_amount: 0,
        card_amount: 350000,
        debt_amount: 0,
        created_at: "2026-09-16T09:15:00.000000Z",
        updated_at: "2026-09-16T09:15:00.000000Z",
        user: DUMMY_CASHIER_USER,
        items: [
            {
                uid: "item-04",
                product_uid: "prod-04",
                nama_produk: "Sirup Markisa Asli 650ml",
                barcode: "BRC-SRP-04",
                harga_beli: 80000,
                harga_satuan: 120000,
                kuantitas: 2,
                diskon_item: 0,
                subtotal: 240000,
            },
            {
                uid: "item-05",
                product_uid: "prod-05",
                nama_produk: "Madu Hutan Murni 500g",
                barcode: "BRC-MDU-05",
                harga_beli: 75000,
                harga_satuan: 110000,
                kuantitas: 1,
                diskon_item: 0,
                subtotal: 110000,
            },
        ],
    },
    {
        uid: "trx-dummy-003",
        store_uid: "store-01",
        user_uid: "user-dummy-01",
        nomor_transaksi: "TRX-20260916-003",
        nama_transaksi: "Grosir Kedai Kopi - Member VIP Budi",
        subtotal: 500000,
        diskon: 0,
        diskon_grosir: 0,
        pajak: 0,
        total: 500000,
        status: "completed",
        metode_pembayaran: "split",
        nominal_bayar: 200000,
        kembalian: 0,
        jenis_kartu: null,
        nomor_kartu_akhir: null,
        cash_received: 200000,
        cash_amount: 200000,
        card_amount: 0,
        debt_amount: 300000,
        created_at: "2026-09-16T10:30:00.000000Z",
        updated_at: "2026-09-16T10:30:00.000000Z",
        user: DUMMY_CASHIER_USER,
        member_uid: "mem-01",
        member: {
            uid: "mem-01",
            kode: "MBR-001",
            nama: "Budi Santoso (Member VIP)",
            nomor_telepon: "08123456789",
            email: "budi@member.local",
            alamat: "Jl. Merdeka No. 10",
            tanggal_lahir: "1990-01-01",
            jenis_kelamin: "L",
            poin: 150,
            status: "active",
            created_at: "2026-01-01T00:00:00.000000Z",
            updated_at: "2026-01-01T00:00:00.000000Z",
        },
        items: [
            {
                uid: "item-06",
                product_uid: "prod-06",
                nama_produk: "Gula Aren Organik 1kg",
                barcode: "BRC-GLA-06",
                harga_beli: 28000,
                harga_satuan: 40000,
                kuantitas: 5,
                diskon_item: 0,
                subtotal: 200000,
            },
            {
                uid: "item-07",
                product_uid: "prod-07",
                nama_produk: "Biji Kopi Robusta Lampung 1kg",
                barcode: "BRC-KOP-07",
                harga_beli: 105000,
                harga_satuan: 150000,
                kuantitas: 2,
                diskon_item: 0,
                subtotal: 300000,
            },
        ],
    },
    {
        uid: "trx-dummy-004",
        store_uid: "store-01",
        user_uid: "user-dummy-01",
        nomor_transaksi: "TRX-20260916-004",
        nama_transaksi: "Batal: Salah Pilih Varian Produk",
        subtotal: 120000,
        diskon: 0,
        diskon_grosir: 0,
        pajak: 0,
        total: 120000,
        status: "void",
        metode_pembayaran: "cash",
        nominal_bayar: 120000,
        kembalian: 0,
        jenis_kartu: null,
        nomor_kartu_akhir: null,
        cash_received: 120000,
        cash_amount: 120000,
        card_amount: 0,
        debt_amount: 0,
        catatan_void: "Pelanggan salah memilih varian rasa dan membatalkan pesanan. Stok dikembalikan otomatis ke gudang.",
        voided_at: "2026-09-16T11:05:00.000000Z",
        void_by_uid: "user-spv-01",
        void_by: DUMMY_SUPERVISOR_USER,
        voidBy: DUMMY_SUPERVISOR_USER,
        created_at: "2026-09-16T11:00:00.000000Z",
        updated_at: "2026-09-16T11:05:00.000000Z",
        user: DUMMY_CASHIER_USER,
        items: [
            {
                uid: "item-08",
                product_uid: "prod-08",
                nama_produk: "Cokelat Bubuk Premium 250g",
                barcode: "BRC-CKL-08",
                harga_beli: 42000,
                harga_satuan: 60000,
                kuantitas: 2,
                diskon_item: 0,
                subtotal: 120000,
            },
        ],
    },
];

export const DUMMY_TRANSACTION_DETAIL: Transaction = DUMMY_TRANSACTIONS[0];

export const DUMMY_TRANSACTIONS_MAP: Record<string, Transaction> = {
    "trx-dummy-001": DUMMY_TRANSACTIONS[0],
    "trx-dummy-002": DUMMY_TRANSACTIONS[1],
    "trx-dummy-003": DUMMY_TRANSACTIONS[2],
    "trx-dummy-004": DUMMY_TRANSACTIONS[3],
};
