import type { CentralReportTutorialStep } from "../types/central-report-tutorial";

export const CENTRAL_REPORT_TUTORIAL_STEPS: CentralReportTutorialStep[] = [
    {
        id: "lk-step-1",
        target: "#central-report-header-info",
        title: "1. Pengenalan Laporan Konsolidasi",
        content: "Selamat datang di Laporan Konsolidasi Multi-Cabang! Fitur ini memberikan gambaran eksekutif tingkat holding yang mengagregasikan performa seluruh cabang toko Anda secara real-time dalam satu tampilan terpadu.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "lk-step-2",
        target: "#central-report-filter-form",
        title: "2. Filter Periode & Multi-Cabang",
        content: "Anda dapat memfilter rentang tanggal, memilih agregasi interval tren (Harian, Mingguan, Bulanan), serta memilih satu, beberapa, atau seluruh cabang sekaligus untuk analisis perbandingan spesifik.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "lk-step-3",
        target: "#central-report-tabs-nav",
        title: "3. 3 Kategori Laporan Konsolidasi",
        content: "Laporan konsolidasi terbagi menjadi 3 pilar analisis utama: (1) Ringkasan Konsolidasi untuk metrik finansial & tren, (2) Perbandingan Cabang untuk matriks komparasi head-to-head, dan (3) Valuasi Stok untuk audit aset inventaris.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "lk-step-4",
        target: "#central-report-kpi-cards",
        title: "4. Tab Ringkasan: 4 Kartu Metrik Finansial",
        content: "Memantau 4 pilar kesehatan keuangan konsolidasi: Penjualan Bersih (omset kotor dikurangi diskon), Laba Kotor (omset dikurangi HPP), Margin Laba Kotor (efisiensi harga pokok), dan Laba Bersih Operasional setelah dipotong seluruh beban cabang.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "lk-step-5",
        target: "#central-report-sales-chart-title",
        title: "5. Tab Ringkasan: Grafik Tren Finansial",
        content: "Memvisualisasikan dinamika pendapatan, laba kotor, dan beban operasional sepanjang periode. Diagram interaktif ini membantu mengidentifikasi tren musiman dan lonjakan pengeluaran.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "lk-step-6",
        target: "#central-report-sales-chart-toggle",
        title: "6. Tab Ringkasan: Sakelar Breakdown Cabang",
        content: "Gunakan sakelar ini untuk beralih antara grafik konsolidasi total atau multi-line chart yang memetakan kurva penjualan masing-masing cabang secara berdampingan.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "lk-step-7",
        target: "#central-report-store-distribution",
        title: "7. Tab Ringkasan: Leaderboard Kontribusi Cabang",
        content: "Daftar peringkat kontribusi penjualan tiap cabang toko terhadap total omset konsolidasi holding, lengkap dengan persentase kontribusi dan status cabang pusat.",
        placement: "left",
        skipScroll: true,
    },
    {
        id: "lk-step-8",
        target: "#central-report-tab-trigger-stores",
        title: "8. Beralih ke Tab Perbandingan Cabang",
        content: "Sekarang, mari kita buka tab 'Perbandingan Cabang' untuk membedah kinerja masing-masing toko secara mendalam.",
        placement: "bottom",
        simulateClick: "#central-report-tab-trigger-stores",
        skipScroll: true,
    },
    {
        id: "lk-step-9",
        target: "#central-report-stores-sample-matrix",
        fallbackTarget: "#central-report-stores-sample-row",
        title: "9. Tab Perbandingan: Matriks Komparasi Cabang",
        content: "Tabel komparasi matriks menyandingkan metrik krusial per cabang: Transaksi, Omset Bersih, Rata-rata Nilai Transaksi (ATV), Laba Kotor & Margin %, Beban Operasional, Laba Bersih, hingga Total Nilai Stok toko.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "lk-step-10",
        target: "#central-report-stores-totals",
        title: "10. Tab Perbandingan: Ringkasan Total Konsolidasi",
        content: "Banner di bawah tabel menyajikan akumulasi total dari seluruh cabang yang dipilih: total transaksi gabungan, total omset, laba kotor, beban, laba bersih, serta total nilai stok keseluruhan.",
        placement: "top",
        skipScroll: true,
    },
    {
        id: "lk-step-11",
        target: "#central-report-tab-trigger-inventory",
        title: "11. Beralih ke Tab Valuasi Stok Cabang",
        content: "Mari berpindah ke tab 'Valuasi Stok' untuk meninjau distribusi aset inventaris dan persediaan barang di setiap cabang.",
        placement: "bottom",
        simulateClick: "#central-report-tab-trigger-inventory",
        skipScroll: true,
    },
    {
        id: "lk-step-12",
        target: "#central-report-inventory-cards",
        title: "12. Tab Valuasi Stok: Ringkasan & Kartu Cabang",
        content: "Menampilkan total valuasi modal persediaan holding, jumlah unit fisik barang, varian SKU aktif, serta rincian nilai modal stok pada masing-masing cabang toko.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "lk-step-13",
        target: "#central-report-inventory-chart-header",
        title: "13. Tab Valuasi Stok: Diagram Komparasi Aset",
        content: "Grafik batang komparasi membandingkan proporsi nilai stok antar cabang secara visual untuk membantu manajemen pemerataan stok dan mencegah over-stock.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "lk-step-14",
        target: "#central-report-btn-print",
        title: "14. Ekspor & Cetak Laporan PDF",
        content: "Anda dapat mencetak atau mengunduh laporan konsolidasi dalam format PDF profesional. Tersedia 2 pilihan dokumen: 'Perbandingan Cabang Toko' dan 'Produk Per Cabang'.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "lk-step-15",
        target: "body",
        title: "15. Panduan Konsolidasi Selesai!",
        content: "Selamat! Anda kini telah memahami seluruh fitur Laporan Konsolidasi Multi-Cabang. Gunakan analisis ini untuk pengambilan keputusan strategis bisnis holding Anda.",
        placement: "center",
        skipScroll: true,
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
