import type { HutangTutorialStep } from "../types/hutang-tutorial";

export const JELAJAH_HUTANG_SALES_TUTORIAL_STEPS: HutangTutorialStep[] = [
    {
        id: "jhs-step-1",
        target: "#hutang-sales-header",
        fallbackTarget: "body",
        title: "1. Halaman Hutang Sales",
        content: "Halaman ini merangkum hutang usaha (utang dagang) ke supplier yang timbul dari transaksi pembelian tempo.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jhs-step-2",
        target: "#hutang-sales-summary",
        title: "2. Ringkasan Hutang",
        content: "Dua kartu menampilkan jumlah supplier yang memiliki hutang dan total akumulasi sisa hutang ke supplier.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jhs-step-3",
        target: "#hutang-sales-filter-form",
        title: "3. Pencarian Supplier",
        content: "Cari supplier berdasarkan nama, telepon, atau email untuk mempersempit daftar hutang.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jhs-step-4",
        target: "#hutang-sales-table",
        title: "4. Daftar Hutang Per Supplier",
        content: "Kolom Total Nilai Faktur, Total Dibayar, dan Sisa Hutang membantu memantau kewajiban ke tiap supplier.",
        placement: "top",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jhs-step-5",
        target: "#hutang-sales-btn-detail",
        fallbackTarget: "#hutang-sales-table",
        title: "5. Tombol Detail",
        content: "Tombol ini membuka rincian hutang per transaksi penerimaan barang. Buka lewat menu Panduan 'Detail Hutang Supplier' untuk menjelajahinya.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "jhs-step-6",
        target: "body",
        title: "6. Selesai: Hutang Supplier Terpahami",
        content: "Monitorkan hutang supplier secara berkala agar pelunasan tempo tidak terlewatkan. Rincian per faktur tersedia di halaman Detail.",
        placement: "center",
        skipScroll: true,
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
