import type { HutangTutorialStep } from "../types/hutang-tutorial";

export const JELAJAH_HUTANG_SUPPLIER_TUTORIAL_STEPS: HutangTutorialStep[] = [
    {
        id: "jhd-step-1",
        target: "#hutang-detail-header",
        fallbackTarget: "body",
        title: "1. Detail Hutang Supplier",
        content: "Halaman ini merinci hutang satu supplier per transaksi penerimaan barang, lengkap dengan status pembayaran tiap faktur.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jhd-step-2",
        target: "#hutang-detail-summary",
        title: "2. Ringkasan Supplier",
        content: "Tiga kartu menampilkan Total Nilai Faktur, Total Dibayar, dan Sisa Hutang supplier terpilih.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jhd-step-3",
        target: "#hutang-detail-filter-form",
        title: "3. Filter Transaksi",
        content: "Cari nomor penerimaan/faktur dan saring berdasarkan rentang tanggal penerimaan barang.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jhd-step-4",
        target: "#hutang-detail-table",
        title: "4. Daftar Hutang Penerimaan",
        content: "Setiap faktur menampilkan nilai faktur, total dibayar, sisa hutang, dan status bayar (Lunas/Sebagian/Belum Bayar).",
        placement: "top",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jhd-step-5",
        target: "#hutang-detail-row-select",
        fallbackTarget: "#hutang-detail-table",
        title: "5. Pilih Faktur Belum Lunas",
        content: "Centang faktur yang ingin dilunasi. Checkbox hanya aktif untuk faktur yang belum lunas.",
        placement: "bottom",
        skipScroll: true,
        simulateClick: "#hutang-detail-row-select",
    },
    {
        id: "jhd-step-6",
        target: "#hutang-detail-btn-bulk-pay",
        title: "6. Pelunasan Sekaligus",
        content: "Tombol ini membuka dialog pelunasan massal untuk faktur terpilih. Pada mode tutorial kita berhenti di sini — pelunasan tidak akan difinalkan.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "jhd-step-7",
        target: "body",
        title: "7. Selesai: Rincian Hutang Terpahami",
        content: "Gunakan tombol kembali untuk melihat supplier lain. Rincian per faktur memudahkan rekonsiliasi pelunasan hutang dagang.",
        placement: "center",
        skipScroll: true,
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
