import type { HutangTutorialStep } from "../types/hutang-tutorial";

export const JELAJAH_HUTANG_MEMBER_TUTORIAL_STEPS: HutangTutorialStep[] = [
    {
        id: "jhm-step-1",
        target: "#hutang-member-header",
        fallbackTarget: "body",
        title: "1. Halaman Hutang Member",
        content: "Halaman ini menampilkan daftar piutang member/pelanggan — yaitu sisa tagihan belanja yang belum dilunasi member.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jhm-step-2",
        target: "#hutang-member-summary",
        title: "2. Ringkasan Piutang",
        content: "Dua kartu ringkasan menampilkan jumlah member yang berhutang dan total akumulasi piutang seluruh member.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jhm-step-3",
        target: "#hutang-member-filter-form",
        title: "3. Filter & Pencarian",
        content: "Cari member berdasarkan nama/kode/telepon dan saring berdasarkan status keaktifan member.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jhm-step-4",
        target: "#hutang-member-table",
        title: "4. Tabel Daftar Tagihan",
        content: "Setiap baris memuat kode, nama, kontak, total hutang, dan status member. Anda bisa mengurutkan per kolom.",
        placement: "top",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jhm-step-5",
        target: "#hutang-member-btn-pay",
        fallbackTarget: "#hutang-member-table",
        title: "5. Tombol Bayar Hutang",
        content: "Tombol ini membuka dialog pembayaran hutang member. Klik untuk mulai melunasi tagihan member.",
        placement: "bottom",
        skipScroll: true,
        closeDialog: "#pay-debt-cancel-btn",
    },
    {
        id: "jhm-step-6",
        target: "#pay-debt-dialog-body",
        title: "6. Dialog Pembayaran",
        content: "Pilih metode bayar (Tunai/Kartu), masukkan nominal, lalu perhatikan ringkasan sisa hutang dan kembalian di panel kanan.",
        placement: "bottom",
        skipScroll: true,
        simulateClick: "#hutang-member-btn-pay",
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jhm-step-7",
        target: "#pay-debt-submit-btn",
        title: "7. Simpan Pembayaran (Demo)",
        content: "Tombol ini menyimpan pembayaran hutang. Pada mode tutorial kita berhenti di sini — pembayaran tidak akan difinalkan.",
        placement: "top",
        skipScroll: true,
        // Pastikan dialog terbuka saat masuk step ini (termasuk saat MUNDUR dari
        // step 8), supaya tombol submit di dalam dialog ada di DOM.
        simulateClick: "#hutang-member-btn-pay",
    },
    {
        id: "jhm-step-8",
        target: "body",
        title: "8. Selesai: Alur Pembayaran Dipahami",
        content: "Dialog ditutup dan Anda kembali ke daftar tagihan. Setelah pelunasan, sisa hutang member otomatis berkurang di daftar.",
        placement: "center",
        skipScroll: true,
        closeDialog: "#pay-debt-cancel-btn",
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
