import type { CashTutorialStep } from "../types/cash-tutorial";

export const JELAJAH_KAS_TUTORIAL_STEPS: CashTutorialStep[] = [
    {
        id: "jk-step-1",
        target: "#kas-header",
        fallbackTarget: "body",
        title: "1. Dashboard Kas & Bank",
        content: "Halaman ini adalah pusat pengelolaan kas toko, rekening bank, laci kasir, dan riwayat arus kas (buku kas).",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        closeDialog: "#kas-ledger-detail-close",
    },
    {
        id: "jk-step-2",
        target: "#kas-accounts-list",
        title: "2. Daftar Akun Kas & Saldo",
        content: "Barisan kartu menampilkan setiap akun kas beserta saldo real-time-nya: Kas, Bank, Laci Kasir, atau EDC/QRIS.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        closeDialog: "#kas-ledger-detail-close",
    },
    {
        id: "jk-step-3",
        target: "#kas-first-card",
        fallbackTarget: "#kas-accounts-list",
        title: "3. Filter Mutasi per Akun",
        content: "Klik salah satu kartu akun untuk memfilter buku kas di bawah agar hanya menampilkan mutasi akun tersebut.",
        placement: "bottom",
        skipScroll: true,
        closeDialog: "#kas-ledger-detail-close",
    },
    {
        id: "jk-step-4",
        target: "#kas-filter-bar",
        title: "4. Filter & Pencarian Mutasi",
        content: "Saring arus kas berdasarkan kata kunci, kategori transaksi (penjualan, pengeluaran, dll), dan rentang tanggal.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        closeDialog: "#kas-ledger-detail-close",
    },
    {
        id: "jk-step-5",
        target: "#kas-ledger-table-scroll",
        fallbackTarget: "#kas-ledger-table",
        title: "5. Buku Kas (Arus Kas Masuk/Keluar)",
        content: "Log transaksi kas otomatis dari penjualan POS, pengeluaran operasional, penerimaan stok, hingga mutasi manual.",
        placement: "top",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        closeDialog: "#kas-ledger-detail-close",
    },
    {
        id: "jk-step-6",
        target: "#kas-ledger-table tbody tr:first-child .table-action-view",
        fallbackTarget: "#kas-ledger-table",
        title: "6. Aksi Rincian Mutasi",
        content: "Tombol ini membuka rincian audit sebuah mutasi: asal transaksi, akun CoA lawan, waktu, dan operator penginput.",
        placement: "bottom",
        skipScroll: true,
        closeDialog: "#kas-ledger-detail-close",
    },
    {
        id: "jk-step-7",
        target: "#kas-ledger-detail-content",
        title: "7. Rincian Audit Mutasi",
        content: "Detail mutasi menampilkan nominal, jenis (debit/kredit/transfer), akun CoA lawan, serta waktu pembuatan data.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        simulateClick: "#kas-ledger-table tbody tr:first-child .table-action-view",
    },
    {
        id: "jk-step-8",
        target: "#kas-header",
        fallbackTarget: "body",
        title: "8. Selesai: Integrasi Otomatis",
        content: "Saldo kas diperbarui otomatis dari modul penjualan, kasir, pengeluaran, dan pembelian. Pantau selalu dari buku kas ini.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        closeDialog: "#kas-ledger-detail-close",
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
