import type { CashTutorialStep } from "../types/cash-tutorial";

export const MUTASI_KAS_TUTORIAL_STEPS: CashTutorialStep[] = [
    {
        id: "mk-step-1",
        target: "#kas-first-card-btn-in",
        fallbackTarget: "#kas-first-card",
        title: "1. Tombol Mutasi Kas",
        content: "Setiap kartu akun punya tombol cepat: In untuk mencatat uang masuk (debit) dan Out untuk uang keluar (kredit) manual.",
        placement: "bottom",
        skipScroll: true,
        // Pastikan dialog tertutup saat masuk step ini (termasuk mundur dari step 3).
        closeDialog: "#kas-mutation-dialog-close",
    },
    {
        id: "mk-step-2",
        target: "#kas-mutation-dialog-body",
        title: "2. Dialog Mutasi Kas",
        content: "Dialog ini mencatat mutasi kas langsung ke akun terpilih tanpa melalui transaksi penjualan atau pembelian.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        // Buka dialog saat masuk step ini (maju dari step 1 maupun mundur dari step 3+).
        simulateClick: "#kas-first-card-btn-in",
    },
    {
        id: "mk-step-3",
        target: "#kas-mutation-amount",
        fallbackTarget: "#kas-mutation-dialog-body",
        title: "3. Nominal Transaksi",
        content: "Masukkan jumlah uang yang disetorkan ke kas (debit) atau ditarik dari kas (kredit).",
        placement: "bottom",
        skipScroll: true,
        simulateClick: "#kas-first-card-btn-in",
    },
    {
        id: "mk-step-4",
        target: "#kas-mutation-coa",
        fallbackTarget: "#kas-mutation-dialog-body",
        title: "4. Akun Lawan (Chart of Accounts)",
        content: "Hubungkan mutasi kas ke akun CoA lawan agar jurnal akuntansi tetap konsisten dan seimbang.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        simulateClick: "#kas-first-card-btn-in",
    },
    {
        id: "mk-step-5",
        target: "#kas-mutation-fields",
        fallbackTarget: "#kas-mutation-dialog-body",
        title: "5. Kategori & Catatan",
        content: "Beri label kategori (mis. modal awal, prive) serta keterangan singkat transaksi untuk penelusuran.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        simulateClick: "#kas-first-card-btn-in",
    },
    {
        id: "mk-step-6",
        target: "#kas-mutation-submit",
        fallbackTarget: "#kas-mutation-dialog-body",
        title: "6. Catat Mutasi (Demo)",
        content: "Tombol ini mencatat mutasi dan langsung memperbarui saldo kas. Pada mode tutorial kita berhenti di sini — data tidak disimpan.",
        placement: "top",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        closeDialog: "#kas-mutation-dialog-close",
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
