import type { CashTutorialStep } from "../types/cash-tutorial";

export const TRANSFER_KAS_TUTORIAL_STEPS: CashTutorialStep[] = [
    {
        id: "tk-step-1",
        target: "#kas-btn-transfer",
        fallbackTarget: "#kas-header",
        title: "1. Tombol Transfer Saldo",
        content: "Gunakan tombol ini untuk memindahkan saldo antar rekening bank, kas toko, atau laci kasir internal.",
        placement: "bottom",
        skipScroll: true,
        // Pastikan dialog tertutup saat masuk step ini (termasuk mundur dari step 3).
        closeDialog: "#kas-transfer-dialog-close",
    },
    {
        id: "tk-step-2",
        target: "#kas-transfer-dialog-body",
        title: "2. Formulir Transfer Saldo",
        content: "Dialog ini memindahkan dana antar akun kas internal toko tanpa memengaruhi laporan penjualan/pengeluaran.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        // Buka dialog saat masuk step ini (maju dari step 1 maupun mundur dari step 3+).
        simulateClick: "#kas-btn-transfer",
    },
    {
        id: "tk-step-3",
        target: "#kas-transfer-from",
        fallbackTarget: "#kas-transfer-dialog-body",
        title: "3. Akun Kas Asal",
        content: "Pilih akun pengirim dana (sumber saldo) dan pastikan saldo tersedia mencukupi nominal transfer.",
        placement: "bottom",
        skipScroll: true,
        simulateClick: "#kas-btn-transfer",
    },
    {
        id: "tk-step-4",
        target: "#kas-transfer-to",
        fallbackTarget: "#kas-transfer-dialog-body",
        title: "4. Akun Kas Tujuan",
        content: "Tentukan akun kas atau rekening bank yang akan menerima dana. Akun asal & tujuan tidak boleh sama.",
        placement: "bottom",
        skipScroll: true,
        simulateClick: "#kas-btn-transfer",
    },
    {
        id: "tk-step-5",
        target: "#kas-transfer-amount-notes",
        fallbackTarget: "#kas-transfer-dialog-body",
        title: "5. Nominal & Catatan Transfer",
        content: "Masukkan nominal rupiah serta alasan transfer, misalnya setoran harian kasir ke rekening bank.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        simulateClick: "#kas-btn-transfer",
    },
    {
        id: "tk-step-6",
        target: "#kas-transfer-submit",
        fallbackTarget: "#kas-transfer-dialog-body",
        title: "6. Eksekusi Transfer (Demo)",
        content: "Tombol ini memproses transfer dan menyesuaikan kedua saldo akun. Pada mode tutorial kita berhenti di sini — dana tidak dipindahkan.",
        placement: "top",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        closeDialog: "#kas-transfer-dialog-close",
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
