import type { SettingsTutorialId, SettingsTutorialStep } from "../types/settings-tutorial";

export const SETTINGS_TUTORIAL_STEPS: Record<SettingsTutorialId, SettingsTutorialStep[]> = {
    ubah_identitas_toko: [
        {
            target: "#settings-tab-profile",
            tabId: "profile",
            title: "1. Tab Identitas Toko",
            content: "Klik tab ini untuk mengelola informasi dasar toko: logo resmi, nama gerai, telepon, dan alamat yang tercetak di struk.",
            placement: "right",
            disableBeacon: true,
        },
        {
            target: "#app_name",
            tabId: "profile",
            title: "2. Nama Toko",
            content: "Nama toko akan muncul di bagian header struk belanja pelanggan dan judul aplikasi kasir.",
            placement: "bottom",
            disableBeacon: true,
            autoFill: {
                label: "Isi Nama Contoh",
                target: "app_name",
                value: "Toko Mitra Sejahtera",
            },
        },
        {
            target: "#app_phone",
            tabId: "profile",
            title: "3. Nomor Telepon Toko",
            content: "Nomor telepon/kontak yang dicetak di struk belanja agar pelanggan dapat menghubungi toko Anda.",
            placement: "bottom",
            disableBeacon: true,
            autoFill: {
                label: "Isi Telepon Contoh",
                target: "app_phone",
                value: "081234567890",
            },
        },
        {
            target: "#app_address",
            tabId: "profile",
            title: "4. Alamat Lengkap Toko",
            content: "Alamat fisik gerai yang akan ditampilkan pada baris alamat di struk belanja transaksi.",
            placement: "top",
            disableBeacon: true,
            autoFill: {
                label: "Isi Alamat Contoh",
                target: "app_address",
                value: "Jl. Merdeka No. 10, Jakarta Pusat",
            },
        },
        {
            target: "#btn-simpan-pengaturan",
            tabId: "profile",
            title: "5. Simpan Perubahan",
            content: "Setelah selesai mengubah profil toko, klik tombol 'Simpan' pada action bar di bawah untuk menyimpan pembaruan ke server.",
            placement: "top",
            disableBeacon: true,
        },
    ],

    atur_ppn_poin: [
        {
            target: "#settings-tab-finance",
            tabId: "finance",
            title: "1. Tab Keuangan & Pajak",
            content: "Tab ini digunakan untuk mengonfigurasi pajak PPN transaksi kasir dan mekanisme poin loyalitas pelanggan.",
            placement: "right",
            disableBeacon: true,
        },
        {
            target: "#tax_rate_ppn",
            tabId: "finance",
            title: "2. Tarif Pajak (PPN %)",
            content: "Persentase PPN default untuk transaksi penjualan. Contoh standar di Indonesia adalah 11%.",
            placement: "bottom",
            disableBeacon: true,
            autoFill: {
                label: "Set PPN 11%",
                target: "tax_rate_ppn",
                value: 11,
            },
        },
        {
            target: "#form-settings-point-toggle",
            tabId: "finance",
            title: "3. Sistem Poin Loyalitas",
            content: "Aktifkan sakelar ini agar member mendapatkan poin setiap kali berbelanja di kasir toko Anda.",
            placement: "bottom",
            disableBeacon: true,
        },
        {
            target: "#point_rate",
            tabId: "finance",
            title: "4. Rasio Poin Belanja (Rp per Poin)",
            content: "Tentukan berapa Rupiah nilai belanja yang setara dengan 1 poin. Misal 10.000: tiap kelipatan Rp 10.000 bernilai 1 poin.",
            placement: "top",
            disableBeacon: true,
            autoFill: {
                label: "Set Rp 10.000 / Poin",
                target: "point_rate",
                value: 10000,
            },
        },
        {
            target: "#btn-simpan-pengaturan",
            tabId: "finance",
            title: "5. Simpan Pengaturan Keuangan",
            content: "Klik tombol 'Simpan' untuk menerapkan perubahan tarif PPN dan rasio poin loyalitas.",
            placement: "top",
            disableBeacon: true,
        },
    ],

    atur_hpp_cabang: [
        {
            target: "#settings-tab-inventory",
            tabId: "inventory",
            title: "1. Tab Inventori & Produk",
            content: "Kelola metode perhitungan HPP dan hak pembuatan produk baru bagi toko cabang.",
            placement: "right",
            disableBeacon: true,
        },
        {
            target: "#form-settings-hpp-select",
            tabId: "inventory",
            title: "2. Metode Penyesuaian HPP",
            content: "Pilih antara 'Latest' (harga faktur beli terakhir) atau 'Average' (rata-rata tertimbang stok lama + barang masuk baru).",
            placement: "bottom",
            disableBeacon: true,
        },
        {
            target: "#form-settings-branch-toggle",
            tabId: "inventory",
            title: "3. Wewenang Produk Cabang",
            content: "Jika aktif, cabang diizinkan menambah katalog barang mandiri. Jika nonaktif, hanya pusat yang mengelola katalog master.",
            placement: "top",
            disableBeacon: true,
        },
        {
            target: "#btn-simpan-pengaturan",
            tabId: "inventory",
            title: "4. Simpan Pengaturan Inventori",
            content: "Klik tombol 'Simpan' untuk menerapkan konfigurasi metode HPP dan hak akses cabang.",
            placement: "top",
            disableBeacon: true,
        },
    ],

    atur_kas: [
        {
            target: "#settings-tab-cash",
            tabId: "cash",
            title: "1. Tab Kas & Operasional Kasir",
            content: "Petakan akun kas penampung transaksi penjualan tunai, saldo internal, dan hak sesi laci kasir.",
            placement: "right",
            disableBeacon: true,
        },
        {
            target: "#form-settings-cash-register",
            tabId: "cash",
            title: "2. Akun Kas Kasir",
            content: "Akun kas default yang otomatis menerima uang tunai saat kasir menyelesaikan penjualan di POS.",
            placement: "bottom",
            disableBeacon: true,
        },
        {
            target: "#form-settings-cash-main",
            tabId: "cash",
            title: "3. Akun Kas Utama",
            content: "Akun kas brankas/utama untuk penampungan dana internal toko dan transfer setoran harian.",
            placement: "bottom",
            disableBeacon: true,
        },
        {
            target: "#form-settings-cash-inout-toggle",
            tabId: "cash",
            title: "4. Izin Cash In / Out Kasir",
            content: "Izinkan kasir mencatat pengeluaran operasional darurat atau penambahan modal kecil selama sesi laci berjalan.",
            placement: "top",
            disableBeacon: true,
        },
        {
            target: "#btn-simpan-pengaturan",
            tabId: "cash",
            title: "5. Simpan Pemetaan Kas",
            content: "Klik 'Simpan' untuk mengunci pemetaan akun kas dan konfigurasi operasional laci kasir.",
            placement: "top",
            disableBeacon: true,
        },
    ],

    atur_printer: [
        {
            target: "#settings-tab-printer",
            tabId: "printer",
            title: "1. Tab Perangkat Printer",
            content: "Kelola konfigurasi printer thermal yang terhubung untuk mencetak struk belanja kasir.",
            placement: "right",
            disableBeacon: true,
        },
        {
            target: "#btn-scan-printer",
            tabId: "printer",
            title: "2. Tombol Pindai Ulang",
            content: "Klik tombol ini untuk mendeteksi ulang printer fisik yang baru dinyalakan atau baru terhubung via USB/Network.",
            placement: "bottom",
            disableBeacon: true,
        },
        {
            target: "#form-settings-printer-select",
            tabId: "printer",
            title: "3. Pilih Printer Default",
            content: "Pilih nama printer thermal yang akan digunakan sistem secara otomatis setiap kali kasir mencetak struk.",
            placement: "top",
            disableBeacon: true,
        },
    ],
};
