import type { Opname, OpnameItem } from "../../types";
import type { StockTutorialMeta } from "../types/stock-tutorial";

export const MOCK_OPNAME_UID = "mock-opname-tut-1";

export const MOCK_OPNAME: Opname = {
    uid: MOCK_OPNAME_UID,
    nomor_opname: "SO-2024-DEMO",
    status: "draft",
    created_at: new Date().toISOString(),
    catatan: "Audit Rutin Bulanan - Toko Pusat",
    items_count: 3,
    user: {
        uid: "user-1",
        name: "Demo Supervisor",
        username: "supervisor",
    },
};

export const MOCK_OPNAME_ITEMS: OpnameItem[] = [
    {
        uid: "mock-op-item-1",
        opname_uid: MOCK_OPNAME_UID,
        product_uid: "mock-prod-1",
        nama: "Kopi Arabika Premium 250g",
        barcode: "8991234567011",
        category_uid: "cat-1",
        brand_uid: "brand-1",
        stok_sistem: 15,
        stok_fisik: 15,
        selisih: 0,
        alasan: null,
        product: {
            uid: "mock-prod-1",
            nama: "Kopi Arabika Premium 250g",
            barcode: "8991234567011",
            harga: 45000,
            stok: 15,
            merek: null,
            status: "active",
        },
    },
    {
        uid: "mock-op-item-2",
        opname_uid: MOCK_OPNAME_UID,
        product_uid: "mock-prod-2",
        nama: "Minyak Goreng Sawit 2L",
        barcode: "8991234567022",
        category_uid: "cat-2",
        brand_uid: "brand-2",
        stok_sistem: 20,
        stok_fisik: 18,
        selisih: -2,
        alasan: "2 botol bocor/pecah di rak belakang",
        product: {
            uid: "mock-prod-2",
            nama: "Minyak Goreng Sawit 2L",
            barcode: "8991234567022",
            harga: 34000,
            stok: 20,
            merek: null,
            status: "active",
        },
    },
    {
        uid: "mock-op-item-3",
        opname_uid: MOCK_OPNAME_UID,
        product_uid: "mock-prod-3",
        nama: "Beras Premium Pandan Wangi 5kg",
        barcode: "8991234567033",
        category_uid: "cat-1",
        brand_uid: "brand-3",
        stok_sistem: 10,
        stok_fisik: 12,
        selisih: 2,
        alasan: "Koreksi retur grosir belum tercatat",
        product: {
            uid: "mock-prod-3",
            nama: "Beras Premium Pandan Wangi 5kg",
            barcode: "8991234567033",
            harga: 78000,
            stok: 10,
            merek: null,
            status: "active",
        },
    },
];

export const MOCK_SCANNED_OPNAME_ITEM: OpnameItem = {
    uid: "mock-op-item-4",
    opname_uid: MOCK_OPNAME_UID,
    product_uid: "mock-prod-4",
    nama: "Susu UHT Full Cream 1L",
    barcode: "8991234567890",
    category_uid: "cat-2",
    brand_uid: "brand-1",
    stok_sistem: 24,
    stok_fisik: 25,
    selisih: 1,
    alasan: null,
    product: {
        uid: "mock-prod-4",
        nama: "Susu UHT Full Cream 1L",
        barcode: "8991234567890",
        harga: 19500,
        stok: 24,
        merek: null,
        status: "active",
    },
};

export const MOCK_ADJUSTMENT_PRODUCT = {
    uid: "mock-prod-adj-1",
    nama: "Kopi Arabika Premium 250g",
    barcode: "8991234567011",
    harga: 45000,
    stok: 15,
    merek: null,
    status: "active",
};

export const MOCK_STOCK_MOVEMENTS = [
    {
        uid: "mock-mv-1",
        product_uid: "mock-prod-1",
        tipe: "sale",
        kuantitas: -2,
        stok_sebelum: 15,
        stok_sesudah: 13,
        alasan: "Penjualan Kasir POS Nota #TRX-20260916-0042 (2 item dibeli pelanggan)",
        created_at: new Date().toISOString(),
        product: {
            uid: "mock-prod-1",
            nama: "Kopi Arabika Premium 250g",
            sku: "KAP-001",
            barcode: "8991234567011",
            harga: 45000,
            stok: 13,
            status: "active",
        },
        user: {
            uid: "usr-cashier",
            name: "Rizky (Kasir Utama)",
            username: "cashier1",
        },
    },
    {
        uid: "mock-mv-2",
        product_uid: "mock-prod-1",
        tipe: "adjustment",
        kuantitas: -2,
        stok_sebelum: 17,
        stok_sesudah: 15,
        alasan: "Penyesuaian stok rusak: 2 kemasan sobek saat display di rak kasir depan",
        created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
        product: {
            uid: "mock-prod-1",
            nama: "Kopi Arabika Premium 250g",
            sku: "KAP-001",
            barcode: "8991234567011",
            harga: 45000,
            stok: 15,
            status: "active",
        },
        user: {
            uid: "usr-admin",
            name: "Budi Santoso (Admin)",
            username: "admin",
        },
    },
    {
        uid: "mock-mv-3",
        product_uid: "mock-prod-1",
        tipe: "receive",
        kuantitas: 10,
        stok_sebelum: 7,
        stok_sesudah: 17,
        alasan: "Penerimaan PO #PO-2026-0088 dari Supplier PT Aneka Pangan Sejahtera",
        created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
        product: {
            uid: "mock-prod-1",
            nama: "Kopi Arabika Premium 250g",
            sku: "KAP-001",
            barcode: "8991234567011",
            harga: 45000,
            stok: 17,
            status: "active",
        },
        user: {
            uid: "usr-warehouse",
            name: "Agus Staf Gudang",
            username: "warehouse",
        },
    },
    {
        uid: "mock-mv-4",
        product_uid: "mock-prod-1",
        tipe: "transfer_out",
        kuantitas: -5,
        stok_sebelum: 12,
        stok_sesudah: 7,
        alasan: "Pengiriman Transfer Stok Cabang ke Outlet Mitra Barat #TRF-OUT-2026-0019",
        created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
        product: {
            uid: "mock-prod-1",
            nama: "Kopi Arabika Premium 250g",
            sku: "KAP-001",
            barcode: "8991234567011",
            harga: 45000,
            stok: 7,
            status: "active",
        },
        user: {
            uid: "usr-admin",
            name: "Budi Santoso (Admin)",
            username: "admin",
        },
    },
    {
        uid: "mock-mv-5",
        product_uid: "mock-prod-1",
        tipe: "production_in",
        kuantitas: 12,
        stok_sebelum: 0,
        stok_sesudah: 12,
        alasan: "Hasil pengerjaan produksi #PRD-20260907-0005",
        created_at: new Date(Date.now() - 3600000 * 72).toISOString(),
        product: {
            uid: "mock-prod-1",
            nama: "Kopi Arabika Premium 250g",
            sku: "KAP-001",
            barcode: "8991234567011",
            harga: 45000,
            stok: 12,
            status: "active",
        },
        user: {
            uid: "usr-admin",
            name: "Budi Santoso (Admin)",
            username: "admin",
        },
    },
    {
        uid: "mock-mv-6",
        product_uid: "mock-prod-1",
        tipe: "stock_out",
        kuantitas: -1,
        stok_sebelum: 12,
        stok_sesudah: 11,
        alasan: "Pemakaian operasional toko (sampel tester)",
        created_at: new Date(Date.now() - 3600000 * 96).toISOString(),
        product: {
            uid: "mock-prod-1",
            nama: "Kopi Arabika Premium 250g",
            sku: "KAP-001",
            barcode: "8991234567011",
            harga: 45000,
            stok: 11,
            status: "active",
        },
        user: {
            uid: "usr-cashier",
            name: "Rizky (Kasir Utama)",
            username: "cashier1",
        },
    },
];

export const STOCK_TUTORIAL_METAS: StockTutorialMeta[] = [
    {
        id: "stock_opname",
        title: "Panduan Lengkap Stock Opname",
        description:
            "Pelajari alur audit fisik barang toko: unduh template/dokumen, pilih metode upload Excel atau scan barcode manual, verifikasi selisih, hingga finalisasi otomatis.",
        badge: "Fitur Opname",
        duration: "3-4 Menit",
        stepCount: 14,
        isAvailable: true,
    },
    {
        id: "stock_adjustment",
        title: "Panduan Penyesuaian Stok (Stock Adjustment)",
        description:
            "Koreksi cepat kuantitas stok produk tertentu akibat barang rusak, bocor, kadaluarsa, atau hilang tanpa perlu membuat sesi audit opname massal.",
        badge: "Penyesuaian",
        duration: "2 Menit",
        stepCount: 9,
        isAvailable: true,
    },
    {
        id: "stock_ledger",
        title: "Panduan Kartu Stok (Audit Mutasi)",
        description:
            "Pelajari cara melacak buku besar mutasi stok barang (masuk/keluar/penyesuaian), audit trail saldo sebelum vs sesudah, filter tipe, dan catatan riwayat.",
        badge: "Buku Besar",
        duration: "2 Menit",
        stepCount: 8,
        isAvailable: true,
    },
];
