import type { ReportsTutorialStep } from "../types/reports-tutorial";

export const JELAJAH_LABA_RUGI_TUTORIAL_STEPS: ReportsTutorialStep[] = [
    {
        id: "jlr-step-1",
        target: "#laba-rugi-header",
        title: "1. Halaman Laba Rugi",
        content: "Halaman ini menampilkan analisis pendapatan, HPP (COGS), diskon, dan keuntungan bersih toko pada periode terpilih.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jlr-step-2",
        target: "#laba-rugi-filter-form",
        title: "2. Filter Periode & Interval",
        content: "Tentukan interval analisis (Harian, Mingguan, Bulanan, Tahunan) serta rentang tanggal laporan, lalu terapkan filter.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jlr-step-3",
        target: "#laba-rugi-summary-card",
        title: "3. Ringkasan KPI Laba / Rugi",
        content: "Kartu ringkasan menampilkan Laba/Rugi Bersih (Profit/Loss) serta breakdown Penjualan Kotor, HPP, Diskon, Laba Penjualan, dan Total Pengeluaran.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jlr-step-4",
        target: "#laba-rugi-tabs",
        title: "4. Tab Rincian Transaksi",
        content: "Beralih antara tampilan Semua transaksi, khusus Penjualan, atau khusus Pengeluaran untuk fokus analisis.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "jlr-step-5",
        target: "#laba-rugi-details-table",
        title: "5. Tabel Rincian Laba Rugi",
        content: "Setiap baris memuat tanggal, nomor faktur, penjualan, HPP, diskon, laba/rugi, dan margin keuntungan per transaksi.",
        placement: "top",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jlr-step-6",
        target: "#laba-rugi-btn-refresh",
        title: "6. Muat Ulang Data",
        content: "Tombol ini memuat ulang laporan sesuai filter terbaru yang Anda terapkan.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "jlr-step-7",
        target: "#laba-rugi-btn-print",
        title: "7. Cetak Laporan PDF",
        content: "Buka konfigurasi cetak untuk memilih ukuran kertas dan orientasi sebelum mengunduh laporan dalam format PDF.",
        placement: "bottom",
        skipScroll: true,
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
