import type { ReportsTutorialStep } from "../types/reports-tutorial";

export const JELAJAH_PENJUALAN_TUTORIAL_STEPS: ReportsTutorialStep[] = [
    {
        id: "jp-step-1",
        target: "#penjualan-header",
        title: "1. Halaman Laporan Penjualan",
        content: "Halaman ini merangkum faktur penjualan barang keluar beserta detail barang yang terjual.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jp-step-2",
        target: "#penjualan-filter-form",
        title: "2. Filter Tanggal",
        content: "Tentukan rentang tanggal penjualan yang ingin dianalisis, lalu terapkan filter untuk memuat data.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jp-step-3",
        target: "#penjualan-switch-items",
        title: "3. Sertakan Detail Barang",
        content: "Sakelar ini menentukan apakah nama dan qty barang terjual ditampilkan saat baris faktur diperluas dan pada cetakan PDF.",
        placement: "bottom",
        skipScroll: true,
        ensureSwitchOn: "#penjualan-switch-items [data-slot='switch'][role='switch']",
    },
    {
        id: "jp-step-4",
        target: "#penjualan-summary-card",
        title: "4. Ringkasan Penjualan",
        content: "Kartu ringkasan menampilkan total nilai penjualan bersih dan volume faktur yang tercatat pada periode terpilih.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jp-step-5",
        target: "#penjualan-details-table",
        title: "5. Tabel Faktur Penjualan",
        content: "Daftar faktur penjualan. Klik salah satu baris untuk membuka rincian barang di dalamnya.",
        placement: "top",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jp-step-6",
        target: "#penjualan-row-expand",
        fallbackTarget: "#penjualan-details-table",
        title: "6. Ekspansi Detail Barang",
        content: "Tombol panah ini membuka detail nama barang, satuan, qty, dan harga jual pada faktur terkait.",
        placement: "bottom",
        skipScroll: true,
        simulateClick: "#penjualan-row-expand",
    },
    {
        id: "jp-step-7",
        target: "#penjualan-btn-print",
        title: "7. Cetak Laporan PDF",
        content: "Buka konfigurasi cetak untuk mengunduh laporan penjualan dalam format PDF siap pakai.",
        placement: "bottom",
        skipScroll: true,
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
