import type { ReportsTutorialStep } from "../types/reports-tutorial";

export const JELAJAH_PEMBELIAN_TUTORIAL_STEPS: ReportsTutorialStep[] = [
    {
        id: "jpb-step-1",
        target: "#pembelian-header",
        title: "1. Halaman Laporan Pembelian",
        content: "Halaman ini merangkum faktur pembelian barang masuk beserta nilai retur dan sisa hutang kepada supplier.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jpb-step-2",
        target: "#pembelian-filter-form",
        title: "2. Filter Tanggal & Opsi",
        content: "Tentukan rentang tanggal serta aktifkan opsi untuk menyertakan daftar barang dan riwayat pembayaran.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jpb-step-3",
        target: "#pembelian-summary-card",
        title: "3. Ringkasan Pembelian",
        content: "Kartu ringkasan menampilkan Total Pembelian Bersih, Total Faktur (kotor), nilai retur, sisa hutang, dan volume faktur.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jpb-step-4",
        target: "#pembelian-details-table",
        title: "4. Tabel Faktur Pembelian",
        content: "Daftar faktur pembelian dengan kolom supplier, status bayar, retur, net, dan sisa hutang. Klik baris untuk detail.",
        placement: "top",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jpb-step-5",
        target: "#pembelian-row-expand",
        fallbackTarget: "#pembelian-details-table",
        title: "5. Ekspansi Detail Faktur",
        content: "Tombol panah ini membuka daftar barang yang dibeli dan riwayat pembayaran pada faktur terkait.",
        placement: "bottom",
        skipScroll: true,
        simulateClick: "#pembelian-row-expand",
    },
    {
        id: "jpb-step-6",
        target: "#pembelian-btn-refresh",
        title: "6. Muat Ulang Data",
        content: "Memuat ulang laporan pembelian sesuai filter terbaru yang diterapkan.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "jpb-step-7",
        target: "#pembelian-btn-print",
        title: "7. Cetak Laporan PDF",
        content: "Buka konfigurasi cetak untuk mengunduh laporan pembelian dalam format PDF siap pakai.",
        placement: "bottom",
        skipScroll: true,
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
