import type { ReportsTutorialStep } from "../types/reports-tutorial";

export const JELAJAH_KATEGORI_TUTORIAL_STEPS: ReportsTutorialStep[] = [
    {
        id: "jk-step-1",
        target: "#kategori-header",
        title: "1. Penjualan Per Kategori",
        content: "Halaman ini menganalisis kontribusi penjualan berdasarkan kategori produk, lengkap dengan grafik dan tabel.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jk-step-2",
        target: "#kategori-filter-form",
        title: "2. Filter Tanggal & Kategori",
        content: "Pilih rentang tanggal dan, jika perlu, pilih satu atau beberapa kategori produk tertentu untuk difokuskan.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jk-step-3",
        target: "#kategori-period-chips",
        fallbackTarget: "#kategori-filter-form",
        title: "3. Ringkasan Periode",
        content: "Chip ini menampilkan periode aktif dan jumlah kategori yang sedang dianalisis pada laporan.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "jk-step-4",
        target: "#kategori-chart",
        title: "4. Grafik Per Kategori",
        content: "Bar chart membandingkan total penjualan (biru) dan keuntungan bersih (hijau) setiap kategori.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jk-step-5",
        target: "#kategori-table",
        title: "5. Tabel Detail & Kontribusi",
        content: "Tabel menampilkan rincian penjualan, total keuntungan, qty, dan bar kontribusi persentase tiap kategori.",
        placement: "top",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jk-step-6",
        target: "#kategori-btn-refresh",
        title: "6. Muat Ulang Data",
        content: "Memuat ulang grafik dan tabel sesuai filter terbaru yang diterapkan.",
        placement: "bottom",
        skipScroll: true,
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
