import type { ReportsTutorialStep } from "../types/reports-tutorial";

export const JELAJAH_PENGELUARAN_TUTORIAL_STEPS: ReportsTutorialStep[] = [
    {
        id: "jpe-step-1",
        target: "#pengeluaran-header",
        title: "1. Halaman Laporan Pengeluaran",
        content: "Halaman ini menampilkan rangkuman dan log rincian biaya pengeluaran kas operasional toko.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jpe-step-2",
        target: "#pengeluaran-filter-form",
        title: "2. Filter Tanggal",
        content: "Tentukan rentang tanggal pengeluaran yang ingin dilihat, lalu terapkan filter untuk memuat data.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jpe-step-3",
        target: "#pengeluaran-summary-card",
        title: "3. Ringkasan Pengeluaran",
        content: "Kartu ringkasan menampilkan Total Nilai Pengeluaran dan frekuensi (jumlah) pencatatan pengeluaran.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jpe-step-4",
        target: "#pengeluaran-details-table",
        title: "4. Tabel Daftar Pengeluaran",
        content: "Setiap baris memuat tanggal, nomor pengeluaran, kategori, keterangan, sumber kas, dan jumlah pengeluaran.",
        placement: "top",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jpe-step-5",
        target: "#pengeluaran-btn-refresh",
        title: "5. Muat Ulang Data",
        content: "Memuat ulang laporan pengeluaran sesuai filter terbaru yang diterapkan.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "jpe-step-6",
        target: "#pengeluaran-btn-print",
        title: "6. Cetak Laporan PDF",
        content: "Buka konfigurasi cetak untuk mengunduh laporan pengeluaran dalam format PDF siap pakai.",
        placement: "bottom",
        skipScroll: true,
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
