import type { CatalogTutorialStep } from "../types/catalog-tutorial";

export const CATALOG_ASSIGN_TUTORIAL_STEPS: CatalogTutorialStep[] = [
    {
        id: "cat-assign-step-1",
        target: "#catalog-table-sample-row",
        fallbackTarget: "#catalog-table-container",
        title: "1. Konsep Distribusi Produk ke Cabang",
        content: "Setelah produk master terdaftar di holding, langkah krusial berikutnya adalah mendistribusikannya ke masing-masing cabang agar dapat dijual dan dikelola stoknya.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "cat-assign-step-2",
        target: "#catalog-action-assign-btn-sample",
        fallbackTarget: "#catalog-table-sample-row",
        title: "2. Tombol Kelola Distribusi Toko",
        content: "Klik tombol ikon toko hijau pada baris produk yang ingin didistribusikan. Sistem akan membuka dialog penugasan cabang secara otomatis.",
        placement: "bottom",
        simulateClick: "#catalog-action-assign-btn-sample",
        skipScroll: true,
    },
    {
        id: "cat-assign-step-3",
        target: "#catalog-assign-product-summary",
        fallbackTarget: "#catalog-assign-form",
        title: "3. Ringkasan Produk Master",
        content: "Banner atas menampilkan identitas produk master: Barcode, Nama Produk, Modal Beli (HPP), dan Harga Jual standar holding sebagai acuan penetapan harga cabang.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "cat-assign-step-4",
        target: "#catalog-assign-global-price",
        fallbackTarget: "#catalog-assign-global-preset",
        title: "4. Preset Global: Harga Jual Seragam",
        content: "Jika ingin seluruh toko menerapkan harga seragam yang berbeda dari master, isi nominal di sini. Jika dikosongkan, seluruh toko otomatis mengikuti Harga Master holding.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "cat-assign-step-5",
        target: "#catalog-assign-global-wholesale",
        fallbackTarget: "#catalog-assign-global-preset",
        title: "5. Preset Global: Skema Grosir Seragam",
        content: "Aktifkan switch ini untuk menerapkan aturan grosir (Min. Qty dan Harga Satuan) secara serentak ke seluruh toko cabang terpilih tanpa perlu input manual satu per satu.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "cat-assign-step-6",
        target: "#catalog-assign-stores-toolbar",
        title: "6. Pemilihan Cabang & Pencarian Toko",
        content: "Gunakan kotak centang untuk memilih seluruh toko sekaligus atau pilih toko tertentu. Gunakan input pencarian untuk menemukan cabang toko dengan cepat.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "cat-assign-step-7",
        target: "#catalog-assign-store-status-sample",
        fallbackTarget: "#catalog-assign-store-row-sample",
        title: "7. Status Ketersediaan di Toko",
        content: "Setiap baris toko memperlihatkan status apakah produk sudah 'Terdaftar' di cabang tersebut beserta harga riil yang saat ini sedang berlaku di kasir toko.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "cat-assign-step-8",
        target: "#catalog-assign-store-preview-sample",
        fallbackTarget: "#catalog-assign-store-row-sample",
        title: "8. Pratinjau Harga Efektif Toko",
        content: "Kolom pratinjau menunjukkan nominal harga jual dan skema grosir yang akan aktif di toko ini setelah tombol simpan ditekan.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "cat-assign-step-9",
        target: "#catalog-assign-store-custom-toggle-sample",
        fallbackTarget: "#catalog-assign-store-row-sample",
        title: "9. Tombol Kustomisasi Harga Khusus",
        content: "Jika cabang tertentu memerlukan harga yang berbeda (misal: cabang bandara, mall elit, atau luar pulau), klik tombol 'Kustomisasi' untuk mengaktifkan pengaturan khusus.",
        placement: "bottom",
        simulateClick: "#catalog-assign-store-custom-toggle-sample",
        skipScroll: true,
    },
    {
        id: "cat-assign-step-10",
        target: "#catalog-assign-store-custom-form-sample",
        fallbackTarget: "#catalog-assign-store-row-sample",
        title: "10. Form Penyesuaian Khusus Cabang",
        content: "Masukkan harga jual ritel khusus dan/atau skema grosir tersendiri yang hanya berlaku untuk cabang ini, tanpa mempengaruhi harga di cabang lainnya.",
        placement: "top",
        skipScroll: true,
    },
    {
        id: "cat-assign-step-11",
        target: "#catalog-assign-btn-submit",
        title: "11. Simpan & Terapkan Distribusi",
        content: "Klik tombol 'Simpan Distribusi' untuk menerapkan seluruh penugasan harga ke cabang-cabang terpilih secara instan dan sinkron dengan sistem POS kasir toko.",
        placement: "top",
        skipScroll: true,
    },
    {
        id: "cat-assign-step-12",
        target: "body",
        title: "12. Panduan Distribusi Selesai!",
        content: "Luar biasa! Anda telah memahami seluruh alur pendistribusian produk ke toko. Sekarang produk master Anda siap diperjualbelikan di seluruh cabang yang telah ditentukan.",
        placement: "center",
        skipScroll: true,
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
