import type { CatalogTutorialStep } from "../types/catalog-tutorial";

export const CATALOG_CREATE_TUTORIAL_STEPS: CatalogTutorialStep[] = [
    {
        id: "cat-create-step-1",
        target: "#catalog-header-title",
        title: "1. Pengenalan Katalog Produk Master",
        content: "Selamat datang di Katalog Keseluruhan Produk! Fitur ini merupakan pusat katalog master holding (single source of truth) tempat Anda mendaftarkan, mengelola, dan mendistribusikan produk ke seluruh cabang toko.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "cat-create-step-2",
        target: "#catalog-filter-search",
        title: "2. Pencarian Cepat Produk Master",
        content: "Cari produk dengan cepat berdasarkan kode barcode, SKU, nama produk, maupun merek dagang untuk memeriksa ketersediaan produk di katalog pusat.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "cat-create-step-3",
        target: "#catalog-filter-category",
        fallbackTarget: "#catalog-filter-brand",
        title: "3. Filter Kategori & Merek",
        content: "Saring daftar katalog berdasarkan klasifikasi Kategori bisnis atau Brand/Merek tertentu untuk memudahkan manajemen lini produk spesifik.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "cat-create-step-4",
        target: "#catalog-filter-type-chips",
        title: "4. Segmentasi Tipe Produk",
        content: "Filter katalog berdasarkan jenis produk: Barang Jadi (produk ritel fisik), Bahan Baku (komponen produksi/inventaris), atau Jasa (layanan tanpa stok fisik).",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "cat-create-step-5",
        target: "#catalog-btn-add",
        title: "5. Tombol Tambah Produk Baru",
        content: "Klik tombol '+ Tambah Produk' untuk membuka formulir pembuatan master produk baru. Sistem akan membuka dialog input otomatis.",
        placement: "bottom",
        simulateClick: "#catalog-btn-add",
        skipScroll: true,
    },
    {
        id: "cat-create-step-6",
        target: "#product-form-identity-column",
        title: "6. Form: Identitas Produk & Satuan",
        content: "Isi identitas master produk: Nama Produk, Barcode/SKU (dapat digenerate otomatis atau discan), Tipe Produk, Kategori, Brand, dan Satuan Unit (misal: Pcs, Kg, Botol).",
        placement: "right",
        skipScroll: true,
    },
    {
        id: "cat-create-step-7",
        target: "#product-form-pricing-column",
        title: "7. Form: Modal Beli (HPP), Margin & Harga Jual",
        content: "Tentukan Harga Beli modal (HPP) dan Margin keuntungan yang diinginkan. Sistem akan mengkalkulasi Harga Jual ritel holding secara otomatis, atau sebaliknya.",
        placement: "left",
        skipScroll: true,
    },
    {
        id: "cat-create-step-8",
        target: "#product-form-wholesale-section",
        title: "8. Form: Skema Harga Grosir Bertingkat",
        content: "Aktifkan switch grosir untuk menetapkan harga bertingkat: tentukan Minimal Kuantitas Pembelian (Pcs) dan Harga Satuan Grosir khusus untuk pembelian dalam jumlah besar.",
        placement: "left",
        skipScroll: true,
    },
    {
        id: "cat-create-step-9",
        target: "#product-form-media-column",
        title: "9. Form: Media Gambar & Status Aktif",
        content: "Unggah foto produk berkualitas untuk memudahkan visualisasi di POS kasir dan e-catalog. Pastikan switch 'Status Produk' dalam kondisi aktif.",
        placement: "right",
        skipScroll: true,
    },
    {
        id: "cat-create-step-10",
        target: "body",
        title: "10. Panduan Pembuatan Selesai!",
        content: "Hebat! Anda telah menguasai cara membuat dan mengelola produk master holding. Selanjutnya, Anda dapat membuka panduan 'Manajemen Pendistribusian Produk ke Toko' untuk mengalokasikan produk ini ke cabang-cabang toko.",
        placement: "center",
        skipScroll: true,
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
