import type { ExpensesTutorialStep } from "../types/expenses-tutorial";

export const CATAT_PENGELUARAN_TUTORIAL_STEPS: ExpensesTutorialStep[] = [
    {
        id: "cp-step-1",
        target: "#pengeluaran-header",
        fallbackTarget: "body",
        title: "1. Mulai Mencatat Pengeluaran",
        content: "Kita akan mensimulasikan pencatatan pengeluaran baru. Dimulai dari halaman daftar pengeluaran.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        // Pastikan dialog tertutup saat masuk step ini (termasuk mundur dari step 3).
        closeDialog: "#expense-dialog-close",
    },
    {
        id: "cp-step-2",
        target: "#expense-dialog-body",
        title: "2. Form Catat Pengeluaran",
        content: "Form ini dipakai untuk mencatat pengeluaran baru. Isi kategori, sumber kas, nominal, tanggal, dan keterangan.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        // Buka dialog saat masuk step ini (maju dari step 1 maupun mundur dari step 3+).
        simulateClick: "#pengeluaran-btn-add",
    },
    {
        id: "cp-step-3",
        target: "#expense-dialog-fields-a",
        title: "3. Kategori & Sumber Kas",
        content: "Pilih kategori pengeluaran (mis. Operasional, Perlengkapan) dan akun kas yang menjadi sumber dana pembayaran.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        simulateClick: "#pengeluaran-btn-add",
    },
    {
        id: "cp-step-4",
        target: "#expense-dialog-fields-b",
        title: "4. Nominal & Tanggal",
        content: "Masukkan nominal pengeluaran dan pilih tanggal transaksi terjadinya pengeluaran.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        simulateClick: "#pengeluaran-btn-add",
    },
    {
        id: "cp-step-5",
        target: "#expense-dialog-submit",
        title: "5. Simpan (Demo)",
        content: "Tombol ini menyimpan catatan pengeluaran. Pada mode tutorial kita berhenti di sini — data tidak akan disimpan.",
        placement: "top",
        skipScroll: true,
        simulateClick: "#pengeluaran-btn-add",
    },
    {
        id: "cp-step-6",
        target: "body",
        title: "6. Selesai: Alur Pencatatan Dipahami",
        content: "Dialog ditutup dan Anda kembali ke daftar. Setelah tersimpan, catatan pengeluaran akan muncul di tabel dan memengaruhi saldo kas.",
        placement: "center",
        skipScroll: true,
        closeDialog: "#expense-dialog-close",
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
