import type { ExpensesTutorialStep } from "../types/expenses-tutorial";

export const EDIT_PENGELUARAN_TUTORIAL_STEPS: ExpensesTutorialStep[] = [
    {
        id: "ep-step-1",
        target: "#pengeluaran-table",
        fallbackTarget: "body",
        title: "1. Sunting Catatan yang Ada",
        content: "Kita akan mensimulasikan pengubahan catatan pengeluaran. Pilih baris pada tabel untuk diubah lewat tombol aksi Ubah.",
        placement: "top",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        // Pastikan dialog tertutup saat masuk step ini (termasuk mundur dari step 3).
        closeDialog: "#expense-dialog-close",
    },
    {
        id: "ep-step-2",
        target: "#expense-dialog-body",
        title: "2. Form Ubah Pengeluaran",
        content: "Form ini terbuka dengan data baris yang dipilih sudah terisi. Ubah field yang diperlukan.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        // Buka dialog mode edit saat masuk step ini (maju dari step 1 maupun mundur).
        simulateClick: "#pengeluaran-table tbody tr:first-child .table-action-edit",
    },
    {
        id: "ep-step-3",
        target: "#expense-dialog-fields-a",
        title: "3. Kategori & Sumber Kas",
        content: "Sesuaikan kategori atau sumber kas bila pencatatan sebelumnya kurang tepat.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        simulateClick: "#pengeluaran-table tbody tr:first-child .table-action-edit",
    },
    {
        id: "ep-step-4",
        target: "#expense-dialog-fields-b",
        title: "4. Nominal & Tanggal",
        content: "Perbaiki nominal atau tanggal transaksi agar catatan akurat.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        simulateClick: "#pengeluaran-table tbody tr:first-child .table-action-edit",
    },
    {
        id: "ep-step-5",
        target: "#expense-dialog-submit",
        title: "5. Simpan Perubahan (Demo)",
        content: "Tombol ini menyimpan perubahan. Pada mode tutorial kita berhenti di sini — perubahan tidak akan disimpan.",
        placement: "top",
        skipScroll: true,
        simulateClick: "#pengeluaran-table tbody tr:first-child .table-action-edit",
    },
    {
        id: "ep-step-6",
        target: "body",
        title: "6. Selesai: Alur Ubah Dipahami",
        content: "Dialog ditutup dan Anda kembali ke daftar. Perubahan akan memperbarui catatan serta menyesuaikan saldo kas terkait.",
        placement: "center",
        skipScroll: true,
        closeDialog: "#expense-dialog-close",
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
