import type { ExpensesTutorialStep } from "../types/expenses-tutorial";

export const JELAJAH_PENGELUARAN_TUTORIAL_STEPS: ExpensesTutorialStep[] = [
    {
        id: "jpl-step-1",
        target: "#pengeluaran-header",
        fallbackTarget: "body",
        title: "1. Halaman Catatan Pengeluaran",
        content: "Halaman ini mencatat seluruh transaksi pengeluaran kas operasional toko, seperti listrik, sewa, dan pembelian perlengkapan.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jpl-step-2",
        target: "#pengeluaran-filter-form",
        title: "2. Filter & Pencarian",
        content: "Cari pengeluaran berdasarkan nomor/nama, tentukan rentang tanggal, lalu saring berdasarkan kategori dan sumber kas.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jpl-step-3",
        target: "#pengeluaran-table",
        title: "3. Tabel Riwayat Pengeluaran",
        content: "Setiap baris memuat nomor, tanggal, keperluan, kategori, sumber kas, nominal, status, dan operator yang mencatat.",
        placement: "top",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
    },
    {
        id: "jpl-step-4",
        target: "#pengeluaran-btn-add",
        fallbackTarget: "#pengeluaran-table",
        title: "4. Tombol Catat Pengeluaran",
        content: "Tombol ini membuka form untuk mencatat pengeluaran baru. Alur lengkapnya dijelaskan pada panduan \"Catat Pengeluaran Baru\".",
        placement: "bottom",
        skipScroll: true,
        // Pastikan dialog tertutup saat masuk step ini (termasuk mundur dari step 6).
        closeDialog: "#pengeluaran-void-confirm-cancel",
    },
    {
        id: "jpl-step-5",
        target: "#pengeluaran-table tbody tr:first-child .table-action-edit",
        fallbackTarget: "#pengeluaran-table",
        title: "5. Aksi Ubah",
        content: "Tombol ini membuka form edit untuk menyunting catatan pengeluaran pada baris terkait.",
        placement: "bottom",
        skipScroll: true,
        closeDialog: "#pengeluaran-void-confirm-cancel",
    },
    {
        id: "jpl-step-6",
        target: "#pengeluaran-table tbody tr:first-child .table-action-delete",
        fallbackTarget: "#pengeluaran-table",
        title: "6. Aksi Hapus",
        content: "Menghapus catatan pengeluaran; nominal pengeluaran akan dikembalikan ke saldo akun kas terkait. Klik untuk membuka konfirmasi.",
        placement: "bottom",
        skipScroll: true,
        closeDialog: "#pengeluaran-void-confirm-cancel",
    },
    {
        id: "jpl-step-7",
        target: "#pengeluaran-void-confirm",
        title: "7. Dialog Konfirmasi Hapus",
        content: "Dialog ini mengonfirmasi penghapusan catatan. Pada mode tutorial kita berhenti di sini — penghapusan tidak akan difinalkan.",
        placement: "bottom",
        skipScroll: true,
        variant: "overlay_nav",
        overlayNav: true,
        // Buka dialog saat masuk step ini (maju dari step 6 maupun mundur dari step 8).
        simulateClick: "#pengeluaran-table tbody tr:first-child .table-action-delete",
    },
    {
        id: "jpl-step-8",
        target: "#pengeluaran-upcoming",
        fallbackTarget: "body",
        title: "8. Jadwal Pengeluaran Rutin",
        content: "Pil ini adalah pengingat tagihan rutin yang belum dicatat bulan ini. Selama panduan berjalan ia mengecil agar tidak menutupi tabel; klik untuk membuka daftarnya.",
        placement: "left",
        skipScroll: true,
        // Tutup dialog konfirmasi saat masuk step ini (baik dari step 7 maju).
        closeDialog: "#pengeluaran-void-confirm-cancel",
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
