import type { JournalTutorialStep } from "../types/journal-tutorial";

export const BUAT_JURNAL_TUTORIAL_STEPS: JournalTutorialStep[] = [
    {
        id: "mj-step-1",
        target: "#mj-keterangan",
        title: "1. Keterangan Jurnal",
        content: "Tuliskan deskripsi ringkas maksud transaksi jurnal ini.",
        placement: "bottom",
        skipScroll: true,
        autoFill: {
            label: "✨ Isi Keterangan Demo",
            target: "#mj-keterangan",
            value: "Setoran Modal Kas (Demo)",
            fillIfEmpty: true,
        },
    },
    {
        id: "mj-step-2",
        target: "#mj-tanggal",
        title: "2. Tanggal Transaksi",
        content: "Secara default, tanggal transaksi terisi hari ini. Anda dapat memilih tanggal lain jika ingin mencatat transaksi lampau.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "mj-step-3",
        target: "#mj-coa-trigger-0",
        title: "3. Buka Pemilih Akun Debit",
        content: "Klik area pilih akun pada baris pertama untuk membuka daftar Chart of Accounts (CoA).",
        placement: "bottom",
        skipScroll: true,
        simulateClick: "#mj-coa-trigger-0",
    },
    {
        id: "mj-step-4",
        target: ".coa-picker-select-btn",
        title: "4. Pilih Akun dari Daftar CoA",
        content: "Daftar akun terbuka. Klik tombol Pilih pada baris akun yang digunakan (misal: Kas), atau tekan Lanjut untuk memilih otomatis.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "mj-step-5",
        target: "#mj-coa-trigger-1",
        title: "5. Akun Lawan Kredit",
        content: "Pilih akun pasangan penyeimbang di baris kedua (misal: Modal Pemilik).",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "mj-step-6",
        target: "#mj-debit-input-0 input",
        title: "6. Input Nominal Debit",
        content: "Masukkan jumlah angka pada kolom Debit di baris akun pertama.",
        placement: "bottom",
        skipScroll: true,
        autoFill: {
            label: "✨ Isi Debit 500.000",
            target: "#mj-debit-input-0 input",
            value: "500000",
            fillIfEmpty: true,
        },
    },
    {
        id: "mj-step-7",
        target: "#mj-kredit-input-1 input",
        title: "7. Input Nominal Kredit",
        content: "Masukkan jumlah angka yang sama pada kolom Kredit di baris akun kedua agar seimbang.",
        placement: "bottom",
        skipScroll: true,
        autoFill: {
            label: "✨ Isi Kredit 500.000",
            target: "#mj-kredit-input-1 input",
            value: "500000",
            fillIfEmpty: true,
        },
    },
    {
        id: "mj-step-8",
        target: "#mj-balance-badge",
        title: "8. Indikator Keseimbangan",
        content: "Pastikan lencana status menunjukkan 'Balance' (Total Debit = Total Kredit) sebelum menyimpan.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "mj-step-9",
        target: "#mj-tambah-baris",
        title: "9. Tambah Baris Jurnal Majemuk",
        content: "Gunakan tombol ini jika transaksi membutuhkan lebih dari dua baris entri akun.",
        placement: "bottom",
        skipScroll: true,
    },
    {
        id: "mj-step-10",
        target: "#mj-simpan-draf",
        title: "10. Simpan Draf Jurnal",
        content: "Klik tombol ini untuk menyimpan entri jurnal. Pada mode tutorial ini, submit tidak akan mengubah data riil.",
        placement: "top",
        skipScroll: true,
        isLastStep: true,
        nextLabel: "Selesai",
    },
];
