import type { SettingsTutorialMeta } from "../types/settings-tutorial";

export const SETTINGS_TUTORIAL_LIST: SettingsTutorialMeta[] = [
    {
        id: "ubah_identitas_toko",
        title: "Identitas Toko",
        description: "Ubah nama, nomor telepon, dan alamat toko yang tercetak di struk belanja.",
        category: "Pengaturan Toko",
        stepCount: 5,
        badge: "Profil Dasar",
        adminOnly: false,
        isAvailable: true,
    },
    {
        id: "atur_ppn_poin",
        title: "Pajak PPN & Poin Loyalitas",
        description: "Konfigurasi tarif PPN default transaksi dan rasio perolehan poin belanja pelanggan.",
        category: "Pengaturan Toko",
        stepCount: 5,
        badge: "Keuangan",
        adminOnly: true,
        isAvailable: true,
    },
    {
        id: "atur_hpp_cabang",
        title: "Kalkulasi HPP & Izin Cabang",
        description: "Pilih metode HPP (Latest/Average) dan atur izin pembuatan produk baru di toko cabang.",
        category: "Pengaturan Toko",
        stepCount: 4,
        badge: "Inventori",
        adminOnly: true,
        isAvailable: true,
    },
    {
        id: "atur_kas",
        title: "Pemetaan Akun Kas",
        description: "Tentukan akun kas kasir, kas utama, saldo bank, dan fitur cash in/out laci kasir.",
        category: "Pengaturan Toko",
        stepCount: 5,
        badge: "Kas & Kasir",
        adminOnly: true,
        isAvailable: true,
    },
    {
        id: "atur_printer",
        title: "Perangkat Printer Struk",
        description: "Status koneksi Printer Service, pindai ulang perangkat, dan pilih printer default.",
        category: "Pengaturan Toko",
        stepCount: 3,
        badge: "Hardware",
        adminOnly: false,
        isAvailable: true,
    },
];
